user mosquitto

persistence true
persistence_location /etc/mosquitto/data/
persistence_file mosquitto.db

autosave_interval 60
autosave_on_changes false

max_queued_messages 100000
max_queued_bytes 104857600
max_inflight_messages 20
queue_qos0_messages false

log_dest syslog
connection_messages true
log_type error
log_type warning
log_type notice

listener 1883 127.0.0.1
protocol mqtt
allow_anonymous true

include_dir /etc/mosquitto/conf.d
