BEGIN;

DO $$
BEGIN
  IF NOT EXISTS (SELECT 1 FROM pg_roles WHERE rolname = 'gateway_evidence_ingestor') THEN
    CREATE ROLE gateway_evidence_ingestor NOLOGIN;
  END IF;
  IF NOT EXISTS (SELECT 1 FROM pg_roles WHERE rolname = 'gateway_evidence_collector') THEN
    CREATE ROLE gateway_evidence_collector NOLOGIN;
  END IF;
  IF NOT EXISTS (SELECT 1 FROM pg_roles WHERE rolname = 'gateway_evidence_verifier') THEN
    CREATE ROLE gateway_evidence_verifier NOLOGIN;
  END IF;
END
$$;

CREATE SCHEMA IF NOT EXISTS gateway_evidence AUTHORIZATION telemetry_admin;
ALTER SCHEMA gateway_evidence OWNER TO telemetry_admin;
REVOKE ALL ON SCHEMA gateway_evidence FROM PUBLIC;
GRANT USAGE ON SCHEMA gateway_evidence TO gateway_evidence_ingestor, gateway_evidence_collector, gateway_evidence_verifier;

SET LOCAL ROLE telemetry_admin;

-- Preserve the exact first ChirpStack gateway reception identity on the accepted
-- application row. Existing v1 telemetry remains valid because these are nullable.
-- v2 verification must fail closed / retry when the provenance is absent; it must
-- never reconstruct the join by nearest timestamp.
ALTER TABLE telemetry.uplinks ADD COLUMN IF NOT EXISTS gateway_uplink_id BIGINT;
ALTER TABLE telemetry.uplinks ADD COLUMN IF NOT EXISTS gateway_frequency_hz BIGINT;
ALTER TABLE telemetry.uplinks ADD COLUMN IF NOT EXISTS gateway_context_base64 TEXT;

CREATE TABLE IF NOT EXISTS gateway_evidence.checkpoints (
    checkpoint_id        BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    gateway_id           TEXT NOT NULL,
    checkpoint_version   TEXT NOT NULL,
    segment_id           BIGINT NOT NULL,
    last_sequence        BIGINT NOT NULL,
    last_record_hash     TEXT NOT NULL,
    segment_hash         TEXT NOT NULL,
    gateway_created_at   TIMESTAMPTZ NOT NULL,
    server_received_at   TIMESTAMPTZ NOT NULL DEFAULT now(),
    client_identity      TEXT NOT NULL,
    request_id           TEXT,
    checkpoint_digest    TEXT NOT NULL,
    CONSTRAINT checkpoint_gateway_id_ck CHECK (gateway_id ~ '^[0-9a-f]{16}$'),
    CONSTRAINT checkpoint_version_ck CHECK (checkpoint_version = 'gateway-checkpoint-v1'),
    CONSTRAINT checkpoint_sequence_ck CHECK (segment_id >= 1 AND last_sequence >= 1),
    CONSTRAINT checkpoint_hash_ck CHECK (
      last_record_hash ~ '^[0-9a-f]{64}$'
      AND segment_hash ~ '^[0-9a-f]{64}$'
      AND checkpoint_digest ~ '^[0-9a-f]{64}$'
    ),
    UNIQUE (gateway_id, last_sequence)
);

CREATE OR REPLACE FUNCTION gateway_evidence.enforce_checkpoint_monotonicity()
RETURNS trigger
LANGUAGE plpgsql
AS $$
DECLARE
    accepted_last_sequence BIGINT;
BEGIN
    -- Serialize every checkpoint decision for one canonical Gateway EUI, including
    -- callers that bypass the Go repository. The application uses the same lock key.
    PERFORM pg_advisory_xact_lock(hashtextextended(NEW.gateway_id, 0));

    SELECT max(last_sequence)
      INTO accepted_last_sequence
      FROM gateway_evidence.checkpoints
     WHERE gateway_id = NEW.gateway_id;

    IF accepted_last_sequence IS NOT NULL
       AND NEW.last_sequence < accepted_last_sequence THEN
        RAISE EXCEPTION
          'checkpoint regression for gateway %: new last_sequence % is behind accepted %',
          NEW.gateway_id, NEW.last_sequence, accepted_last_sequence
          USING ERRCODE = '23514';
    END IF;

    RETURN NEW;
END
$$;

DROP TRIGGER IF EXISTS checkpoints_monotonic_before_insert
ON gateway_evidence.checkpoints;
CREATE TRIGGER checkpoints_monotonic_before_insert
BEFORE INSERT ON gateway_evidence.checkpoints
FOR EACH ROW
EXECUTE FUNCTION gateway_evidence.enforce_checkpoint_monotonicity();

CREATE TABLE IF NOT EXISTS gateway_evidence.segments (
    segment_row_id        BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    gateway_id            TEXT NOT NULL,
    segment_version       TEXT NOT NULL,
    segment_id            BIGINT NOT NULL,
    first_sequence        BIGINT NOT NULL,
    last_sequence         BIGINT NOT NULL,
    record_count          BIGINT NOT NULL,
    previous_segment_hash TEXT NOT NULL,
    final_record_hash     TEXT NOT NULL,
    segment_hash          TEXT NOT NULL,
    object_ref            TEXT NOT NULL,
    object_sha256         TEXT NOT NULL,
    uploaded_at           TIMESTAMPTZ NOT NULL DEFAULT now(),
    verify_status         TEXT NOT NULL DEFAULT 'pending',
    verify_error          TEXT,
    CONSTRAINT segment_gateway_id_ck CHECK (gateway_id ~ '^[0-9a-f]{16}$'),
    CONSTRAINT segment_version_ck CHECK (segment_version = 'gateway-journal-segment-v1'),
    CONSTRAINT segment_sequence_ck CHECK (
      segment_id >= 1
      AND first_sequence >= 1
      AND last_sequence >= first_sequence
      AND record_count > 0
    ),
    CONSTRAINT segment_previous_hash_ck CHECK (
      (segment_id = 1 AND previous_segment_hash = 'GENESIS')
      OR (segment_id > 1 AND previous_segment_hash ~ '^[0-9a-f]{64}$')
    ),
    CONSTRAINT segment_hash_ck CHECK (
      final_record_hash ~ '^[0-9a-f]{64}$'
      AND segment_hash ~ '^[0-9a-f]{64}$'
      AND object_sha256 ~ '^[0-9a-f]{64}$'
    ),
    CONSTRAINT segment_status_ck CHECK (
      verify_status IN ('pending','verified','evidence_gap','integrity_failure')
    ),
    UNIQUE (gateway_id, segment_id)
);

CREATE TABLE IF NOT EXISTS gateway_evidence.mqtt_gateway_events (
    gateway_event_id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    gateway_id               TEXT NOT NULL,
    mqtt_topic               TEXT NOT NULL,
    broker_received_at       TIMESTAMPTZ NOT NULL,
    capture_key_sha256       TEXT NOT NULL,
    serialized_event_sha256  TEXT NOT NULL,
    phy_payload_sha256       TEXT,
    uplink_id                TEXT,
    frequency_hz             BIGINT,
    rssi_dbm                 INTEGER,
    snr_db                   DOUBLE PRECISION,
    gateway_context_base64   TEXT,
    correlation_digest_sha256 TEXT,
    collector_version        TEXT NOT NULL,
    object_ref               TEXT,
    CONSTRAINT mqtt_gateway_id_ck CHECK (gateway_id ~ '^[0-9a-f]{16}$'),
    CONSTRAINT mqtt_hash_ck CHECK (
      capture_key_sha256 ~ '^[0-9a-f]{64}$'
      AND serialized_event_sha256 ~ '^[0-9a-f]{64}$'
      AND (phy_payload_sha256 IS NULL OR phy_payload_sha256 ~ '^[0-9a-f]{64}$')
      AND (correlation_digest_sha256 IS NULL OR correlation_digest_sha256 ~ '^[0-9a-f]{64}$')
    ),
    CONSTRAINT mqtt_frequency_ck CHECK (frequency_hz IS NULL OR frequency_hz > 0),
    CONSTRAINT mqtt_projection_ck CHECK (
      (correlation_digest_sha256 IS NULL
       AND phy_payload_sha256 IS NULL AND uplink_id IS NULL AND frequency_hz IS NULL
       AND rssi_dbm IS NULL AND snr_db IS NULL AND gateway_context_base64 IS NULL)
      OR
      (correlation_digest_sha256 IS NOT NULL
       AND phy_payload_sha256 IS NOT NULL AND uplink_id IS NOT NULL AND frequency_hz IS NOT NULL
       AND rssi_dbm IS NOT NULL AND snr_db IS NOT NULL AND gateway_context_base64 IS NOT NULL)
    ),
    CONSTRAINT mqtt_uplink_id_ck CHECK (uplink_id IS NULL OR uplink_id ~ '^[0-9]+$'),
    UNIQUE (capture_key_sha256)
);

-- Upgrade-safe replay of the projection contract if an earlier source-only
-- version of this migration was applied in a disposable development database.
ALTER TABLE gateway_evidence.mqtt_gateway_events
  ADD COLUMN IF NOT EXISTS gateway_context_base64 TEXT;
ALTER TABLE gateway_evidence.mqtt_gateway_events
  DROP CONSTRAINT IF EXISTS mqtt_projection_ck;
ALTER TABLE gateway_evidence.mqtt_gateway_events
  ADD CONSTRAINT mqtt_projection_ck CHECK (
    (correlation_digest_sha256 IS NULL
     AND phy_payload_sha256 IS NULL AND uplink_id IS NULL AND frequency_hz IS NULL
     AND rssi_dbm IS NULL AND snr_db IS NULL AND gateway_context_base64 IS NULL)
    OR
    (correlation_digest_sha256 IS NOT NULL
     AND phy_payload_sha256 IS NOT NULL AND uplink_id IS NOT NULL AND frequency_hz IS NOT NULL
     AND rssi_dbm IS NOT NULL AND snr_db IS NOT NULL AND gateway_context_base64 IS NOT NULL)
  );

CREATE TABLE IF NOT EXISTS gateway_evidence.event_verification (
    verification_id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    source_event_key         TEXT NOT NULL,
    observed_at              TIMESTAMPTZ NOT NULL,
    gateway_id               TEXT,
    journal_segment_id       BIGINT,
    journal_sequence         BIGINT,
    journal_record_hash      TEXT,
    journal_segment_hash     TEXT,
    checkpoint_id            BIGINT REFERENCES gateway_evidence.checkpoints(checkpoint_id) ON DELETE RESTRICT,
    gateway_event_id         BIGINT REFERENCES gateway_evidence.mqtt_gateway_events(gateway_event_id) ON DELETE RESTRICT,
    decoder_id               TEXT,
    decoder_version          TEXT,
    raw_app_data_sha256      TEXT,
    normalized_digest_sha256 TEXT,
    status                   TEXT NOT NULL DEFAULT 'pending',
    reason_code              TEXT,
    worker_id                TEXT,
    lease_expires_at         TIMESTAMPTZ,
    attempts                 INTEGER NOT NULL DEFAULT 0,
    next_attempt_at          TIMESTAMPTZ NOT NULL DEFAULT now(),
    verified_at              TIMESTAMPTZ,
    created_at               TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at               TIMESTAMPTZ NOT NULL DEFAULT now(),
    CONSTRAINT verification_source_key_ck CHECK (length(source_event_key) > 0),
    CONSTRAINT verification_gateway_id_ck CHECK (gateway_id IS NULL OR gateway_id ~ '^[0-9a-f]{16}$'),
    CONSTRAINT verification_sequence_ck CHECK (
      (journal_segment_id IS NULL OR journal_segment_id >= 1)
      AND (journal_sequence IS NULL OR journal_sequence >= 1)
      AND attempts >= 0
    ),
    CONSTRAINT verification_hash_ck CHECK (
      (journal_record_hash IS NULL OR journal_record_hash ~ '^[0-9a-f]{64}$')
      AND (journal_segment_hash IS NULL OR journal_segment_hash ~ '^[0-9a-f]{64}$')
      AND (raw_app_data_sha256 IS NULL OR raw_app_data_sha256 ~ '^[0-9a-f]{64}$')
      AND (normalized_digest_sha256 IS NULL OR normalized_digest_sha256 ~ '^[0-9a-f]{64}$')
    ),
    CONSTRAINT verification_status_ck CHECK (
      status IN ('pending','verified','evidence_gap','integrity_failure','not_required')
    ),
    CONSTRAINT verification_terminal_lease_ck CHECK (
      status = 'pending' OR (worker_id IS NULL AND lease_expires_at IS NULL)
    ),
    CONSTRAINT verification_verified_at_ck CHECK (
      (status = 'verified' AND verified_at IS NOT NULL)
      OR (status <> 'verified' AND verified_at IS NULL)
    ),
    CONSTRAINT verification_terminal_reason_ck CHECK (
      status = 'pending'
      OR (status = 'verified' AND reason_code IS NULL)
      OR (status IN ('evidence_gap','integrity_failure','not_required') AND reason_code IS NOT NULL)
    ),
    CONSTRAINT verification_verified_projection_ck CHECK (
      status <> 'verified'
      OR (
        gateway_id IS NOT NULL
        AND journal_segment_id IS NOT NULL
        AND journal_sequence IS NOT NULL
        AND journal_record_hash IS NOT NULL
        AND journal_segment_hash IS NOT NULL
        AND checkpoint_id IS NOT NULL
        AND gateway_event_id IS NOT NULL
        AND decoder_id IS NOT NULL
        AND decoder_version IS NOT NULL
        AND raw_app_data_sha256 IS NOT NULL
        AND normalized_digest_sha256 IS NOT NULL
      )
    ),
    UNIQUE (source_event_key, observed_at)
);

CREATE INDEX IF NOT EXISTS checkpoints_gateway_received_idx
  ON gateway_evidence.checkpoints (gateway_id, server_received_at DESC);
CREATE INDEX IF NOT EXISTS segments_gateway_uploaded_idx
  ON gateway_evidence.segments (gateway_id, uploaded_at DESC);
CREATE INDEX IF NOT EXISTS mqtt_gateway_events_gateway_received_idx
  ON gateway_evidence.mqtt_gateway_events (gateway_id, broker_received_at DESC);
CREATE INDEX IF NOT EXISTS mqtt_gateway_events_uplink_lookup_idx
  ON gateway_evidence.mqtt_gateway_events (gateway_id, uplink_id, frequency_hz, gateway_context_base64)
  WHERE correlation_digest_sha256 IS NOT NULL;
CREATE INDEX IF NOT EXISTS event_verification_pending_idx
  ON gateway_evidence.event_verification (next_attempt_at, verification_id)
  WHERE status = 'pending';
CREATE INDEX IF NOT EXISTS event_verification_status_observed_idx
  ON gateway_evidence.event_verification (status, observed_at DESC);

CREATE OR REPLACE VIEW gateway_evidence.checkpoint_status AS
SELECT DISTINCT ON (gateway_id)
  gateway_id,
  checkpoint_id,
  segment_id,
  last_sequence,
  server_received_at,
  now() - server_received_at AS checkpoint_age
FROM gateway_evidence.checkpoints
ORDER BY gateway_id, last_sequence DESC, checkpoint_id DESC;

CREATE OR REPLACE VIEW gateway_evidence.verification_status AS
SELECT
  verification_id,
  source_event_key,
  observed_at,
  gateway_id,
  status,
  reason_code,
  attempts,
  next_attempt_at,
  lease_expires_at,
  verified_at,
  created_at,
  updated_at
FROM gateway_evidence.event_verification;

REVOKE ALL ON ALL TABLES IN SCHEMA gateway_evidence FROM PUBLIC;
REVOKE ALL ON ALL SEQUENCES IN SCHEMA gateway_evidence FROM PUBLIC;

GRANT SELECT ON gateway_evidence.checkpoints, gateway_evidence.segments TO gateway_evidence_ingestor;
GRANT INSERT (
  gateway_id,
  checkpoint_version,
  segment_id,
  last_sequence,
  last_record_hash,
  segment_hash,
  gateway_created_at,
  client_identity,
  request_id,
  checkpoint_digest
) ON gateway_evidence.checkpoints TO gateway_evidence_ingestor;
GRANT INSERT (
  gateway_id,
  segment_version,
  segment_id,
  first_sequence,
  last_sequence,
  record_count,
  previous_segment_hash,
  final_record_hash,
  segment_hash,
  object_ref,
  object_sha256
) ON gateway_evidence.segments TO gateway_evidence_ingestor;
GRANT USAGE, SELECT ON SEQUENCE gateway_evidence.checkpoints_checkpoint_id_seq, gateway_evidence.segments_segment_row_id_seq TO gateway_evidence_ingestor;

GRANT SELECT ON gateway_evidence.mqtt_gateway_events TO gateway_evidence_collector;
GRANT INSERT (
  gateway_id,
  mqtt_topic,
  broker_received_at,
  capture_key_sha256,
  serialized_event_sha256,
  phy_payload_sha256,
  uplink_id,
  frequency_hz,
  rssi_dbm,
  snr_db,
  gateway_context_base64,
  correlation_digest_sha256,
  collector_version,
  object_ref
) ON gateway_evidence.mqtt_gateway_events TO gateway_evidence_collector;
GRANT USAGE, SELECT ON SEQUENCE gateway_evidence.mqtt_gateway_events_gateway_event_id_seq TO gateway_evidence_collector;

GRANT SELECT ON gateway_evidence.checkpoints, gateway_evidence.segments, gateway_evidence.mqtt_gateway_events, gateway_evidence.event_verification TO gateway_evidence_verifier;
GRANT UPDATE (verify_status, verify_error) ON gateway_evidence.segments TO gateway_evidence_verifier;
GRANT INSERT (source_event_key, observed_at) ON gateway_evidence.event_verification TO gateway_evidence_verifier;
GRANT USAGE, SELECT ON SEQUENCE gateway_evidence.event_verification_verification_id_seq TO gateway_evidence_verifier;
GRANT UPDATE (
  gateway_id,
  journal_segment_id,
  journal_sequence,
  journal_record_hash,
  journal_segment_hash,
  checkpoint_id,
  gateway_event_id,
  decoder_id,
  decoder_version,
  raw_app_data_sha256,
  normalized_digest_sha256,
  status,
  reason_code,
  worker_id,
  lease_expires_at,
  attempts,
  next_attempt_at,
  verified_at,
  updated_at
) ON gateway_evidence.event_verification TO gateway_evidence_verifier;

GRANT USAGE ON SCHEMA telemetry TO gateway_evidence_verifier;
GRANT SELECT ON telemetry.uplinks, telemetry.measurements, telemetry.fabric_outbox TO gateway_evidence_verifier;

RESET ROLE;

DO $$
BEGIN
  IF EXISTS (SELECT 1 FROM pg_roles WHERE rolname = 'telemetry_reader') THEN
    GRANT USAGE ON SCHEMA gateway_evidence TO telemetry_reader;
    GRANT SELECT ON gateway_evidence.checkpoint_status, gateway_evidence.verification_status TO telemetry_reader;
  END IF;
  IF EXISTS (SELECT 1 FROM pg_roles WHERE rolname = 'fabric_adapter') THEN
    GRANT USAGE ON SCHEMA gateway_evidence TO fabric_adapter;
    GRANT SELECT ON gateway_evidence.event_verification TO fabric_adapter;
  END IF;
END
$$;

COMMIT;
